#!/bin/sh

# (C) 2007, Robert Bradshaw, William Hart, William Stein, Michael Abshoff

if [ "`uname`" = "Linux" -a "`uname -m`" = "x86_64" ]; then
   FLINT_TUNE="-funroll-loops "
elif [ "`uname`" = "Darwin" -a "`uname -m`" = "Power Macintosh" ]; then
   FLINT_TUNE=" -funroll-loops "
elif [ "`uname -p`" = "powerpc" ]; then
   FLINT_TUNE="-m64 -mcpu=970 -mtune=970 -mpowerpc64 -falign-loops=16 -falign-functions=16 -falign-labels=16 -falign-jumps=16"
elif [ "`uname -m`" = "ia64" ]; then 
   # -funroll-loops crashes the build on itanium under GCC-4.2.1, as reported by
   # Kate Minola.
   FLINT_TUNE=" "
else
   FLINT_TUNE="-O2 -funroll-loops "
fi

if [ "`uname`" = "Darwin" ]; then
   FLINT_LIB="libflint.dylib"
else 
   FLINT_LIB="libflint.so"
fi 

export FLINT_TUNE
export FLINT_LIB

if [ -z "$FLINT_GMP_INCLUDE_DIR" ]
then
	FLINT_GMP_INCLUDE_DIR="/home/wbhart/mpir-2.1.1"
fi
export FLINT_GMP_INCLUDE_DIR

if [ -z "$FLINT_MPFR_INCLUDE_DIR" ]
then
        FLINT_MPFR_INCLUDE_DIR="/home/wbhart/mpfr-3.0.0/"
fi
export FLINT_GMP_INCLUDE_DIR

if [ -z "$FLINT_GMP_LIB_DIR" ]
then
    FLINT_GMP_LIB_DIR="/home/wbhart/mpir-2.1.1/.libs"
fi
export FLINT_GMP_LIB_DIR

if [ -z "$FLINT_MPFR_LIB_DIR" ]
then
    FLINT_MPFR_LIB_DIR="/home/wbhart/mpfr-3.0.0/.libs"
fi
export FLINT_GMP_LIB_DIR

if [ -z "$FLINT_LINK_OPTIONS" ]
then
	FLINT_LINK_OPTIONS=""
fi
export FLINT_LINK_OPTION

if [ -z "${LD_LIBRARY_PATH}" ]
then
	LD_LIBRARY_PATH=$FLINT_GMP_LIB_DIR:$FLINT_MPFR_LIB_DIR
fi
export LD_LIBRARY_PATH

if [ -z "$FLINT_NTL_INCLUDE_DIR" ]
then
        FLINT_NTL_INCLUDE_DIR="/usr/local/sage/sage-4.5.3/local/include"
fi
export FLINT_NTL_INCLUDE_DIR

if [ -z "$FLINT_NTL_LIB_DIR" ]
then
        FLINT_NTL_LIB_DIR="/usr/local/sage/sage-4.5.3/local/lib"
fi
export FLINT_NTL_LIB_DIR
