###############################################################################
#
# Script for generating profiling information tables for C modules being
# profiled by profiler-main.c.
#
# It takes one command-line parameter: the name of the module, e.g. "xyz".
# It reads through xyz-profile.c, pulls out function names having certain
# initial substrings, and builds a file xyz-profile-tables.c which should
# be linked against xyz-profile.c and profiler-main.c.
#
# See the makefile for typical usage. See also profiler-main.c.
#
# (C) 2007 William Hart and David Harvey
#
###############################################################################


import sys
import re


if len(sys.argv) != 2:
   raise ValueError, "no file specified"
   
module = sys.argv[1]


############ process input file

cfilename = module + "-profile.c"
cfile = open(cfilename)

prof2dMain_re = re.compile("void prof2dMain_(.*)\(.*")
prof2dExec_re = re.compile("void prof2dExec_(.*)\(.*")
prof2dString_re = re.compile("char prof2dString_(.*)\[\].*")

prof2d_re = [prof2dMain_re, prof2dExec_re, prof2dString_re]

# dictionary from profile name to a triple of bools, indicating which of
# main, exec, string are defined
prof2d_data = {}

for line in cfile:
   for i in range(len(prof2d_re)):
      m = prof2d_re[i].match(line)
      if m is not None:
         name = m.group(1)
         if name not in prof2d_data:
            prof2d_data[name] = [False, False, False]
         else:
            if prof2d_data[name][i]:
               raise ValueError, "duplicate target \"%s\"" % name
         prof2d_data[name][i] = True


############ generate output file

tfilename = module + "-profile-tables.c"
tfile = open(tfilename, "w")

tfile.write(
   "/* ===================================================================\n"
   "\n"
   "   " + tfilename + "\n"
   "\n"
   "   This file was AUTOMATICALLY GENERATED by make-profile-tables.py.\n"
   "   DO NOT EDIT IT -- your changes will go the way of all LOST SOCKS.\n"
   "\n"
   "=================================================================== */\n"
   "\n"
)

tfile.write("#include <stdlib.h>\n")
tfile.write("#include \"profiler-main.h\"\n")
tfile.write("\n")

tfile.write("char* prof_module_name = \"" + module + "\";\n\n")

tfile.write("int prof2d_target_count = %s;\n\n" % len(prof2d_data))

for (name, flags) in prof2d_data.iteritems():
   if flags[0]:
      tfile.write("extern void prof2dMain_%s();\n" % name)
   if flags[1]:
      tfile.write("extern void prof2dExec_%s(unsigned long, unsigned long, unsigned long);\n" % name)
   if flags[2]:
      tfile.write("extern char prof2dString_%s[];\n" % name)
tfile.write("\n")

tfile.write("char* prof2d_target_name[] = {\n")
for (name, flags) in prof2d_data.iteritems():
   tfile.write("   \"%s\",\n" % name)
tfile.write("};\n\n")

tfile.write("char* prof2d_target_string[] = {\n")
for (name, flags) in prof2d_data.iteritems():
   tfile.write("   prof2dString_%s,\n" % name  if flags[2] else "   NULL,\n")
tfile.write("};\n\n")

tfile.write("prof2d_exec_t prof2d_target_exec[] = {\n")
for (name, flags) in prof2d_data.iteritems():
   tfile.write("   prof2dExec_%s,\n" % name  if flags[1] else "   NULL,\n")
tfile.write("};\n\n")

tfile.write("prof2d_main_t prof2d_target_main[] = {\n")
for (name, flags) in prof2d_data.iteritems():
   tfile.write("   prof2dMain_%s,\n" % name  if flags[0] else "   NULL,\n")
tfile.write("};\n\n")


########### end of file
