/*
   Tuning values for mpz_poly module

   Automatically generated by mpz_poly-tune program
*/

#include "mpz_poly-tuning.h"
#include "mpz_poly.h"

unsigned long mpz_poly_kara_crossover_table[] = {9, 7, 6, 5, 4, 4, 3, 0};
unsigned long mpz_poly_kara_crossover_table_size = 8;


// end of file *********************************
