/*============================================================================

    This file is part of FLINT.

    FLINT is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    FLINT is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with FLINT; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

===============================================================================*/
/*
   Tuning values for mpz_poly module

   Automatically generated by mpz_poly-tune program
*/

#include "mpz_poly-tuning.h"
#include "mpz_poly.h"

unsigned long mpz_poly_kara_crossover_table[] = {9, 7, 6, 5, 4, 4, 3, 0};
unsigned long mpz_poly_kara_crossover_table_size = 8;


// end of file *********************************
