/*
   Tuning values for ZmodF_mul module

   Automatically generated by ZmodF_mul-tune program
*/

#include "ZmodF_mul-tuning.h"
#include "ZmodF_mul.h"

unsigned long ZmodF_mul_plain_threeway_threshold = 24;
unsigned long ZmodF_mul_plain_fft_threshold = 265;
unsigned long ZmodF_mul_threeway_fft_threshold = 471;
unsigned long ZmodF_mul_fft_table[20] =
   {252, 561, 1183, 2555, 5368, 14973, 60163, 0};

unsigned long ZmodF_sqr_plain_threeway_threshold = 36;
unsigned long ZmodF_sqr_plain_fft_threshold = 560;
unsigned long ZmodF_sqr_threeway_fft_threshold = 330;
unsigned long ZmodF_sqr_fft_table[20] =
   {153, 359, 796, 2144, 4314, 14977, 60163, 0};


// end of file *********************************
