/*
   NOTE: do not edit this file! It is auto-generated by the "tune" program.
   (Run "make tune" and then "./tune > tuning.c" to regenerate it.)
*/

/*
   tuning.c:  global tuning values

   Copyright (C) 2007, 2008, David Harvey

   This file is part of the zn_poly library (version 0.8).

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 2 of the License, or
   (at your option) version 3 of the License.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

#include "zn_poly_internal.h"

tuning_info_t tuning_info[] = 
{
   {  // bits = 0
   },
   {  // bits = 1
   },
   {  // bits = 2
        132,   // KS1 -> KS2 multiplication crossover
       1053,   // KS2 -> KS4 multiplication crossover
   SIZE_MAX,   // KS4 -> FFT multiplication crossover
        158,   // KS1 -> KS2 squaring crossover
       1053,   // KS2 -> KS4 squaring crossover
   SIZE_MAX,   // KS4 -> FFT squaring crossover
       6889,   // fallback -> FFT middle product crossover
         13,   // nussbaumer multiplication crossover
         12    // nussbaumer squaring crossover
   },
   {  // bits = 3
        132,   // KS1 -> KS2 multiplication crossover
       1540,   // KS2 -> KS4 multiplication crossover
   SIZE_MAX,   // KS4 -> FFT multiplication crossover
        132,   // KS1 -> KS2 squaring crossover
       2755,   // KS2 -> KS4 squaring crossover
      28087,   // KS4 -> FFT squaring crossover
       6889,   // fallback -> FFT middle product crossover
         12,   // nussbaumer multiplication crossover
         12    // nussbaumer squaring crossover
   },
   {  // bits = 4
         86,   // KS1 -> KS2 multiplication crossover
        985,   // KS2 -> KS4 multiplication crossover
   SIZE_MAX,   // KS4 -> FFT multiplication crossover
        102,   // KS1 -> KS2 squaring crossover
       1053,   // KS2 -> KS4 squaring crossover
      32051,   // KS4 -> FFT squaring crossover
       4817,   // fallback -> FFT middle product crossover
         12,   // nussbaumer multiplication crossover
         12    // nussbaumer squaring crossover
   },
   {  // bits = 5
         72,   // KS1 -> KS2 multiplication crossover
        616,   // KS2 -> KS4 multiplication crossover
      32051,   // KS4 -> FFT multiplication crossover
        108,   // KS1 -> KS2 squaring crossover
        689,   // KS2 -> KS4 squaring crossover
      18901,   // KS4 -> FFT squaring crossover
       4817,   // fallback -> FFT middle product crossover
         12,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 6
         75,   // KS1 -> KS2 multiplication crossover
        901,   // KS2 -> KS4 multiplication crossover
   SIZE_MAX,   // KS4 -> FFT multiplication crossover
        108,   // KS1 -> KS2 squaring crossover
        901,   // KS2 -> KS4 squaring crossover
      14515,   // KS4 -> FFT squaring crossover
       4212,   // fallback -> FFT middle product crossover
         12,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 7
         75,   // KS1 -> KS2 multiplication crossover
        377,   // KS2 -> KS4 multiplication crossover
      20868,   // KS4 -> FFT multiplication crossover
        102,   // KS1 -> KS2 squaring crossover
        451,   // KS2 -> KS4 squaring crossover
      17119,   // KS4 -> FFT squaring crossover
       3445,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 8
         56,   // KS1 -> KS2 multiplication crossover
        431,   // KS2 -> KS4 multiplication crossover
      20868,   // KS4 -> FFT multiplication crossover
         67,   // KS1 -> KS2 squaring crossover
        576,   // KS2 -> KS4 squaring crossover
      15505,   // KS4 -> FFT squaring crossover
       3445,   // fallback -> FFT middle product crossover
         12,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 9
         54,   // KS1 -> KS2 multiplication crossover
        264,   // KS2 -> KS4 multiplication crossover
      17119,   // KS4 -> FFT multiplication crossover
         80,   // KS1 -> KS2 squaring crossover
        288,   // KS2 -> KS4 squaring crossover
      14044,   // KS4 -> FFT squaring crossover
       3012,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 10
         56,   // KS1 -> KS2 multiplication crossover
        226,   // KS2 -> KS4 multiplication crossover
      17119,   // KS4 -> FFT multiplication crossover
         80,   // KS1 -> KS2 squaring crossover
        264,   // KS2 -> KS4 squaring crossover
      12307,   // KS4 -> FFT squaring crossover
       3221,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 11
         50,   // KS1 -> KS2 multiplication crossover
        189,   // KS2 -> KS4 multiplication crossover
      15505,   // KS4 -> FFT multiplication crossover
         66,   // KS1 -> KS2 squaring crossover
        216,   // KS2 -> KS4 squaring crossover
      14044,   // KS4 -> FFT squaring crossover
       2755,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 12
         43,   // KS1 -> KS2 multiplication crossover
        132,   // KS2 -> KS4 multiplication crossover
      12307,   // KS4 -> FFT multiplication crossover
         66,   // KS1 -> KS2 squaring crossover
        173,   // KS2 -> KS4 squaring crossover
       8560,   // KS4 -> FFT squaring crossover
       2755,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 13
         46,   // KS1 -> KS2 multiplication crossover
        144,   // KS2 -> KS4 multiplication crossover
      14044,   // KS4 -> FFT multiplication crossover
         57,   // KS1 -> KS2 squaring crossover
        189,   // KS2 -> KS4 squaring crossover
      12307,   // KS4 -> FFT squaring crossover
       2576,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         11    // nussbaumer squaring crossover
   },
   {  // bits = 14
         47,   // KS1 -> KS2 multiplication crossover
        101,   // KS2 -> KS4 multiplication crossover
      10785,   // KS4 -> FFT multiplication crossover
         57,   // KS1 -> KS2 squaring crossover
        141,   // KS2 -> KS4 squaring crossover
       7753,   // KS4 -> FFT squaring crossover
       2576,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 15
         40,   // KS1 -> KS2 multiplication crossover
        144,   // KS2 -> KS4 multiplication crossover
      12307,   // KS4 -> FFT multiplication crossover
         51,   // KS1 -> KS2 squaring crossover
        173,   // KS2 -> KS4 squaring crossover
        720,   // KS4 -> FFT squaring crossover
       2106,   // fallback -> FFT middle product crossover
         11,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 16
         38,   // KS1 -> KS2 multiplication crossover
        102,   // KS2 -> KS4 multiplication crossover
      10785,   // KS4 -> FFT multiplication crossover
         50,   // KS1 -> KS2 squaring crossover
        151,   // KS2 -> KS4 squaring crossover
       7022,   // KS4 -> FFT squaring crossover
       2106,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 17
         33,   // KS1 -> KS2 multiplication crossover
        112,   // KS2 -> KS4 multiplication crossover
      10785,   // KS4 -> FFT multiplication crossover
         47,   // KS1 -> KS2 squaring crossover
        132,   // KS2 -> KS4 squaring crossover
       8560,   // KS4 -> FFT squaring crossover
       1723,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 18
         31,   // KS1 -> KS2 multiplication crossover
         75,   // KS2 -> KS4 multiplication crossover
       7022,   // KS4 -> FFT multiplication crossover
         47,   // KS1 -> KS2 squaring crossover
        112,   // KS2 -> KS4 squaring crossover
       5393,   // KS4 -> FFT squaring crossover
       1842,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 19
         35,   // KS1 -> KS2 multiplication crossover
         78,   // KS2 -> KS4 multiplication crossover
       8560,   // KS4 -> FFT multiplication crossover
         43,   // KS1 -> KS2 squaring crossover
        108,   // KS2 -> KS4 squaring crossover
       7022,   // KS4 -> FFT squaring crossover
       1506,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 20
         33,   // KS1 -> KS2 multiplication crossover
         70,   // KS2 -> KS4 multiplication crossover
       6154,   // KS4 -> FFT multiplication crossover
         43,   // KS1 -> KS2 squaring crossover
         94,   // KS2 -> KS4 squaring crossover
       4726,   // KS4 -> FFT squaring crossover
       1506,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 21
         31,   // KS1 -> KS2 multiplication crossover
         72,   // KS2 -> KS4 multiplication crossover
       7022,   // KS4 -> FFT multiplication crossover
         39,   // KS1 -> KS2 squaring crossover
        102,   // KS2 -> KS4 squaring crossover
       6154,   // KS4 -> FFT squaring crossover
       1205,   // fallback -> FFT middle product crossover
         10,   // nussbaumer multiplication crossover
         10    // nussbaumer squaring crossover
   },
   {  // bits = 22
         31,   // KS1 -> KS2 multiplication crossover
         66,   // KS2 -> KS4 multiplication crossover
       5217,   // KS4 -> FFT multiplication crossover
         40,   // KS1 -> KS2 squaring crossover
         86,   // KS2 -> KS4 squaring crossover
       4726,   // KS4 -> FFT squaring crossover
       1378,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 23
         31,   // KS1 -> KS2 multiplication crossover
         70,   // KS2 -> KS4 multiplication crossover
       7022,   // KS4 -> FFT multiplication crossover
         38,   // KS1 -> KS2 squaring crossover
         86,   // KS2 -> KS4 squaring crossover
       6360,   // KS4 -> FFT squaring crossover
       1288,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 24
         31,   // KS1 -> KS2 multiplication crossover
         66,   // KS2 -> KS4 multiplication crossover
       5760,   // KS4 -> FFT multiplication crossover
         38,   // KS1 -> KS2 squaring crossover
         86,   // KS2 -> KS4 squaring crossover
       4280,   // KS4 -> FFT squaring crossover
       1378,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 25
         27,   // KS1 -> KS2 multiplication crossover
         61,   // KS2 -> KS4 multiplication crossover
       7022,   // KS4 -> FFT multiplication crossover
         35,   // KS1 -> KS2 squaring crossover
         80,   // KS2 -> KS4 squaring crossover
       4726,   // KS4 -> FFT squaring crossover
       1205,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 26
         31,   // KS1 -> KS2 multiplication crossover
         57,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         33,   // KS1 -> KS2 squaring crossover
         75,   // KS2 -> KS4 squaring crossover
       4280,   // KS4 -> FFT squaring crossover
       1127,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 27
         27,   // KS1 -> KS2 multiplication crossover
         56,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         35,   // KS1 -> KS2 squaring crossover
         66,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        985,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 28
         27,   // KS1 -> KS2 multiplication crossover
         51,   // KS2 -> KS4 multiplication crossover
       3877,   // KS4 -> FFT multiplication crossover
         31,   // KS1 -> KS2 squaring crossover
         70,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        862,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 29
         24,   // KS1 -> KS2 multiplication crossover
         54,   // KS2 -> KS4 multiplication crossover
       5217,   // KS4 -> FFT multiplication crossover
         29,   // KS1 -> KS2 squaring crossover
         70,   // KS2 -> KS4 squaring crossover
       4280,   // KS4 -> FFT squaring crossover
        806,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 30
         23,   // KS1 -> KS2 multiplication crossover
         47,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         33,   // KS1 -> KS2 squaring crossover
         66,   // KS2 -> KS4 squaring crossover
       3877,   // KS4 -> FFT squaring crossover
        921,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 31
         24,   // KS1 -> KS2 multiplication crossover
         43,   // KS2 -> KS4 multiplication crossover
       4726,   // KS4 -> FFT multiplication crossover
         31,   // KS1 -> KS2 squaring crossover
         66,   // KS2 -> KS4 squaring crossover
       3877,   // KS4 -> FFT squaring crossover
        862,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 32
         24,   // KS1 -> KS2 multiplication crossover
         39,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         31,   // KS1 -> KS2 squaring crossover
         66,   // KS2 -> KS4 squaring crossover
       3877,   // KS4 -> FFT squaring crossover
        862,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 33
         19,   // KS1 -> KS2 multiplication crossover
         36,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         29,   // KS1 -> KS2 squaring crossover
         57,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        862,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 34
         21,   // KS1 -> KS2 multiplication crossover
         33,   // KS2 -> KS4 multiplication crossover
       3877,   // KS4 -> FFT multiplication crossover
         29,   // KS1 -> KS2 squaring crossover
         56,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        806,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 35
         21,   // KS1 -> KS2 multiplication crossover
         33,   // KS2 -> KS4 multiplication crossover
       3877,   // KS4 -> FFT multiplication crossover
         29,   // KS1 -> KS2 squaring crossover
         43,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        824,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 36
         21,   // KS1 -> KS2 multiplication crossover
         27,   // KS2 -> KS4 multiplication crossover
       3877,   // KS4 -> FFT multiplication crossover
         27,   // KS1 -> KS2 squaring crossover
         45,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        753,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 37
         17,   // KS1 -> KS2 multiplication crossover
         31,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         25,   // KS1 -> KS2 squaring crossover
         43,   // KS2 -> KS4 squaring crossover
       3180,   // KS4 -> FFT squaring crossover
        630,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 38
         19,   // KS1 -> KS2 multiplication crossover
         25,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         27,   // KS1 -> KS2 squaring crossover
         28,   // KS2 -> KS4 squaring crossover
       3180,   // KS4 -> FFT squaring crossover
        689,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 39
         19,   // KS1 -> KS2 multiplication crossover
         27,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         25,   // KS1 -> KS2 squaring crossover
         41,   // KS2 -> KS4 squaring crossover
       3180,   // KS4 -> FFT squaring crossover
        689,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
   {  // bits = 40
         19,   // KS1 -> KS2 multiplication crossover
         27,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         25,   // KS1 -> KS2 squaring crossover
         43,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        689,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 41
         19,   // KS1 -> KS2 multiplication crossover
         25,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         25,   // KS1 -> KS2 squaring crossover
         39,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        689,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 42
         17,   // KS1 -> KS2 multiplication crossover
         25,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         24,   // KS1 -> KS2 squaring crossover
         43,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        603,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 43
         16,   // KS1 -> KS2 multiplication crossover
         25,   // KS2 -> KS4 multiplication crossover
       3180,   // KS4 -> FFT multiplication crossover
         23,   // KS1 -> KS2 squaring crossover
         33,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        616,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 44
         17,   // KS1 -> KS2 multiplication crossover
         23,   // KS2 -> KS4 multiplication crossover
       3180,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         38,   // KS2 -> KS4 squaring crossover
       3511,   // KS4 -> FFT squaring crossover
        564,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 45
         16,   // KS1 -> KS2 multiplication crossover
         25,   // KS2 -> KS4 multiplication crossover
       3511,   // KS4 -> FFT multiplication crossover
         23,   // KS1 -> KS2 squaring crossover
         36,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        360,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 46
         17,   // KS1 -> KS2 multiplication crossover
         21,   // KS2 -> KS4 multiplication crossover
       3180,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         43,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        527,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 47
         16,   // KS1 -> KS2 multiplication crossover
         21,   // KS2 -> KS4 multiplication crossover
       3077,   // KS4 -> FFT multiplication crossover
         21,   // KS1 -> KS2 squaring crossover
         33,   // KS2 -> KS4 squaring crossover
       3077,   // KS4 -> FFT squaring crossover
        527,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 48
         17,   // KS1 -> KS2 multiplication crossover
         21,   // KS2 -> KS4 multiplication crossover
       3077,   // KS4 -> FFT multiplication crossover
         21,   // KS1 -> KS2 squaring crossover
         25,   // KS2 -> KS4 squaring crossover
       2697,   // KS4 -> FFT squaring crossover
        493,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 49
         14,   // KS1 -> KS2 multiplication crossover
         17,   // KS2 -> KS4 multiplication crossover
       2880,   // KS4 -> FFT multiplication crossover
         21,   // KS1 -> KS2 squaring crossover
         25,   // KS2 -> KS4 squaring crossover
       2697,   // KS4 -> FFT squaring crossover
        527,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 50
         14,   // KS1 -> KS2 multiplication crossover
         19,   // KS2 -> KS4 multiplication crossover
       2880,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         36,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        493,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 51
         14,   // KS1 -> KS2 multiplication crossover
         19,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         33,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        461,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 52
         14,   // KS1 -> KS2 multiplication crossover
         19,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         21,   // KS1 -> KS2 squaring crossover
         24,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        412,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 53
         13,   // KS1 -> KS2 multiplication crossover
         17,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         25,   // KS2 -> KS4 squaring crossover
       1876,   // KS4 -> FFT squaring crossover
        377,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 54
         13,   // KS1 -> KS2 multiplication crossover
         19,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         31,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        412,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 55
         13,   // KS1 -> KS2 multiplication crossover
         16,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         19,   // KS2 -> KS4 squaring crossover
       2140,   // KS4 -> FFT squaring crossover
        377,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 56
         13,   // KS1 -> KS2 multiplication crossover
         10,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         17,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        377,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 57
         13,   // KS1 -> KS2 multiplication crossover
         14,   // KS2 -> KS4 multiplication crossover
       2071,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         17,   // KS2 -> KS4 squaring crossover
       2071,   // KS4 -> FFT squaring crossover
        345,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 58
         13,   // KS1 -> KS2 multiplication crossover
         19,   // KS2 -> KS4 multiplication crossover
       2071,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         24,   // KS2 -> KS4 squaring crossover
       2071,   // KS4 -> FFT squaring crossover
        345,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 59
         13,   // KS1 -> KS2 multiplication crossover
         11,   // KS2 -> KS4 multiplication crossover
       2004,   // KS4 -> FFT multiplication crossover
         19,   // KS1 -> KS2 squaring crossover
         21,   // KS2 -> KS4 squaring crossover
       1756,   // KS4 -> FFT squaring crossover
        345,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 60
         13,   // KS1 -> KS2 multiplication crossover
         12,   // KS2 -> KS4 multiplication crossover
       2140,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         19,   // KS2 -> KS4 squaring crossover
       1756,   // KS4 -> FFT squaring crossover
        247,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 61
         13,   // KS1 -> KS2 multiplication crossover
         14,   // KS2 -> KS4 multiplication crossover
       2212,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         19,   // KS2 -> KS4 squaring crossover
       1262,   // KS4 -> FFT squaring crossover
        226,   // fallback -> FFT middle product crossover
          7,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 62
         13,   // KS1 -> KS2 multiplication crossover
         21,   // KS2 -> KS4 multiplication crossover
       2697,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         33,   // KS2 -> KS4 squaring crossover
       2363,   // KS4 -> FFT squaring crossover
        431,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 63
         13,   // KS1 -> KS2 multiplication crossover
         23,   // KS2 -> KS4 multiplication crossover
       2363,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         35,   // KS2 -> KS4 squaring crossover
       2140,   // KS4 -> FFT squaring crossover
        403,   // fallback -> FFT middle product crossover
          8,   // nussbaumer multiplication crossover
          8    // nussbaumer squaring crossover
   },
   {  // bits = 64
         13,   // KS1 -> KS2 multiplication crossover
         23,   // KS2 -> KS4 multiplication crossover
       4280,   // KS4 -> FFT multiplication crossover
         17,   // KS1 -> KS2 squaring crossover
         33,   // KS2 -> KS4 squaring crossover
       4280,   // KS4 -> FFT squaring crossover
        689,   // fallback -> FFT middle product crossover
          9,   // nussbaumer multiplication crossover
          9    // nussbaumer squaring crossover
   },
};

// end of file ****************************************************************
