#!/bin/sh

# (C) 2007, Robert Bradshaw, William Hart, William Stein, Michael Abshoff

if [ "`uname`" = "Linux" -a "`uname -m`" = "x86_64" ]; then
   MPIR_TUNE="-mtune=opteron -march=opteron -funroll-loops "
elif [ "`uname`" = "Darwin" -a "`uname -m`" = "Power Macintosh" ]; then
   MPIR_TUNE=" -funroll-loops "
elif [ "`uname -p`" = "powerpc" ]; then
   MPIR_TUNE="-m64 -mcpu=970 -mtune=970 -mpowerpc64 -falign-loops=16 -falign-functions=16 -falign-labels=16 -falign-jumps=16"
elif [ "`uname -m`" = "ia64" ]; then 
   # -funroll-loops crashes the build on itanium under GCC-4.2.1, as reported by
   # Kate Minola.
   MPIR_TUNE=" "
else
   MPIR_TUNE="-funroll-loops "
fi

if [ "`uname`" = "Darwin" ]; then
   MPIR_LIB="libmpir.dylib"
else 
   MPIR_LIB="libmpir.so"
fi 

export MPIR_TUNE
export MPIR_LIB

if [ -z "$MPIR_GMP_INCLUDE_DIR" ]
then
	MPIR_GMP_INCLUDE_DIR="/usr/local/include"
fi
export MPIR_GMP_INCLUDE_DIR

if [ -z "$MPIR_GMP_LIB_DIR" ]
then
	MPIR_GMP_LIB_DIR="/usr/local/lib"
fi
export MPIR_GMP_LIB_DIR

if [ -z "$MPIR_LINK_OPTIONS" ]
then
	MPIR_LINK_OPTIONS=""
fi
export MPIR_LINK_OPTION

if [ -z "${LD_LIBRARY_PATH}" ]
then
	LD_LIBRARY_PATH=$MPIR_GMP_LIB_DIR
fi
export LD_LIBRARY_PATH
